spring.application.name=biotechnology-mongodb-client
spring.data.mongodb.uri=mongodb://localhost:27017/biotechnology-db
spring.data.mongodb.database=biotechnology-db
spring.main.web-application-type=none
logging.level.root=INFO
